[build]
  base = "packages/nextjs"
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.18.3"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
