import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const externalContracts = {
  84532: {
    MockUSDC: {
      address: "0xCB632653EF8d9642136796D576b868c4040bE3Be",
      abi: [
        {
          inputs: [
            { internalType: "uint256", name: "initialSupply", type: "uint256" },
            { internalType: "address", name: "initialOwner", type: "address" },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        { inputs: [], name: "ECDSAInvalidSignature", type: "error" },
        {
          inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
          name: "ECDSAInvalidSignatureLength",
          type: "error",
        },
        {
          inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }],
          name: "ECDSAInvalidSignatureS",
          type: "error",
        },
        {
          inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "allowance", type: "uint256" },
            { internalType: "uint256", name: "needed", type: "uint256" },
          ],
          name: "ERC20InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            { internalType: "address", name: "sender", type: "address" },
            { internalType: "uint256", name: "balance", type: "uint256" },
            { internalType: "uint256", name: "needed", type: "uint256" },
          ],
          name: "ERC20InsufficientBalance",
          type: "error",
        },
        {
          inputs: [{ internalType: "address", name: "approver", type: "address" }],
          name: "ERC20InvalidApprover",
          type: "error",
        },
        {
          inputs: [{ internalType: "address", name: "receiver", type: "address" }],
          name: "ERC20InvalidReceiver",
          type: "error",
        },
        {
          inputs: [{ internalType: "address", name: "sender", type: "address" }],
          name: "ERC20InvalidSender",
          type: "error",
        },
        {
          inputs: [{ internalType: "address", name: "spender", type: "address" }],
          name: "ERC20InvalidSpender",
          type: "error",
        },
        {
          inputs: [{ internalType: "uint256", name: "deadline", type: "uint256" }],
          name: "ERC2612ExpiredSignature",
          type: "error",
        },
        {
          inputs: [
            { internalType: "address", name: "signer", type: "address" },
            { internalType: "address", name: "owner", type: "address" },
          ],
          name: "ERC2612InvalidSigner",
          type: "error",
        },
        {
          inputs: [
            { internalType: "address", name: "account", type: "address" },
            { internalType: "uint256", name: "currentNonce", type: "uint256" },
          ],
          name: "InvalidAccountNonce",
          type: "error",
        },
        { inputs: [], name: "InvalidShortString", type: "error" },
        {
          inputs: [
            { internalType: "uint256", name: "requested", type: "uint256" },
            { internalType: "uint256", name: "limit", type: "uint256" },
          ],
          name: "MockUSDC__FaucetLimitExceeded",
          type: "error",
        },
        { inputs: [], name: "MockUSDC__ZeroAddress", type: "error" },
        { inputs: [], name: "MockUSDC__ZeroAmount", type: "error" },
        {
          inputs: [{ internalType: "address", name: "owner", type: "address" }],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [{ internalType: "address", name: "account", type: "address" }],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        { inputs: [{ internalType: "string", name: "str", type: "string" }], name: "StringTooLong", type: "error" },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "owner", type: "address" },
            { indexed: true, internalType: "address", name: "spender", type: "address" },
            { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
          ],
          name: "Approval",
          type: "event",
        },
        { anonymous: false, inputs: [], name: "EIP712DomainChanged", type: "event" },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "to", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "Faucet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "to", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "OwnerMint",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
            { indexed: true, internalType: "address", name: "newOwner", type: "address" },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "from", type: "address" },
            { indexed: true, internalType: "address", name: "to", type: "address" },
            { indexed: false, internalType: "uint256", name: "value", type: "uint256" },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [],
          name: "DOMAIN_SEPARATOR",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "address", name: "spender", type: "address" },
          ],
          name: "allowance",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
          ],
          name: "approve",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "account", type: "address" }],
          name: "balanceOf",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "eip712Domain",
          outputs: [
            { internalType: "bytes1", name: "fields", type: "bytes1" },
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "version", type: "string" },
            { internalType: "uint256", name: "chainId", type: "uint256" },
            { internalType: "address", name: "verifyingContract", type: "address" },
            { internalType: "bytes32", name: "salt", type: "bytes32" },
            { internalType: "uint256[]", name: "extensions", type: "uint256[]" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
          name: "faucet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "owner", type: "address" }],
          name: "nonces",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "ownerMint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "owner", type: "address" },
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
            { internalType: "uint256", name: "deadline", type: "uint256" },
            { internalType: "uint8", name: "v", type: "uint8" },
            { internalType: "bytes32", name: "r", type: "bytes32" },
            { internalType: "bytes32", name: "s", type: "bytes32" },
          ],
          name: "permit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
        {
          inputs: [],
          name: "symbol",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
          ],
          name: "transfer",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "from", type: "address" },
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "value", type: "uint256" },
          ],
          name: "transferFrom",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ] as const,
    },
    BodaBodaSavings: {
      address: "0x407457843e3BcDd5476eD8075c4D4e74722DAAd9",
      abi: [
        {
          inputs: [
            { internalType: "address", name: "_stablecoin", type: "address" },
            { internalType: "address[]", name: "_lenderAddrs", type: "address[]" },
            { internalType: "string[]", name: "_lenderNames", type: "string[]" },
            { internalType: "uint256[]", name: "_cycles", type: "uint256[]" },
            { internalType: "enum BodaBodaSavings.RepaymentSchedule[]", name: "_schedules", type: "uint8[]" },
            { internalType: "address", name: "initialOwner", type: "address" },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        { inputs: [], name: "BodaBodaSavings__CannotRecoverStablecoin", type: "error" },
        { inputs: [], name: "BodaBodaSavings__ContractBalanceMustBeZero", type: "error" },
        { inputs: [], name: "BodaBodaSavings__DecimalsMismatch", type: "error" },
        { inputs: [], name: "BodaBodaSavings__ExceedsAvailablePool", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InsufficientLoanBalance", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InsufficientSavings", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InvalidAge", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InvalidCollectionCycle", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InvalidGender", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InvalidKycLevel", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InvalidSplitRatio", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InvalidStablecoinContract", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InvalidVerificationHash", type: "error" },
        { inputs: [], name: "BodaBodaSavings__InvalidWithdrawalCategory", type: "error" },
        { inputs: [], name: "BodaBodaSavings__LenderAlreadyRegistered", type: "error" },
        { inputs: [], name: "BodaBodaSavings__LenderNotActive", type: "error" },
        { inputs: [], name: "BodaBodaSavings__LenderNotFound", type: "error" },
        { inputs: [], name: "BodaBodaSavings__LicenseExpired", type: "error" },
        { inputs: [], name: "BodaBodaSavings__LoanAlreadyCleared", type: "error" },
        { inputs: [], name: "BodaBodaSavings__NameRequired", type: "error" },
        { inputs: [], name: "BodaBodaSavings__NewTargetBelowRepaid", type: "error" },
        { inputs: [], name: "BodaBodaSavings__NoLendersProvided", type: "error" },
        { inputs: [], name: "BodaBodaSavings__NoPotActive", type: "error" },
        { inputs: [], name: "BodaBodaSavings__NoWithdrawalPending", type: "error" },
        { inputs: [], name: "BodaBodaSavings__NoWithdrawalToCancel", type: "error" },
        { inputs: [], name: "BodaBodaSavings__OutstandingAccounting", type: "error" },
        { inputs: [], name: "BodaBodaSavings__PotAlreadyActive", type: "error" },
        { inputs: [], name: "BodaBodaSavings__PotDeadlineNotReached", type: "error" },
        { inputs: [], name: "BodaBodaSavings__RiderAlreadyRegistered", type: "error" },
        { inputs: [], name: "BodaBodaSavings__RiderNotRegistered", type: "error" },
        { inputs: [], name: "BodaBodaSavings__RiderNotVerified", type: "error" },
        { inputs: [], name: "BodaBodaSavings__StablecoinCannotBeZeroAddress", type: "error" },
        { inputs: [], name: "BodaBodaSavings__TransferFailed", type: "error" },
        { inputs: [], name: "BodaBodaSavings__WithdrawalAlreadyPending", type: "error" },
        { inputs: [], name: "BodaBodaSavings__WithdrawalDelayNotMet", type: "error" },
        { inputs: [], name: "BodaBodaSavings__WithdrawalNotApproved", type: "error" },
        { inputs: [], name: "BodaBodaSavings__ZeroAddress", type: "error" },
        { inputs: [], name: "BodaBodaSavings__ZeroAddressToken", type: "error" },
        { inputs: [], name: "BodaBodaSavings__ZeroAmount", type: "error" },
        { inputs: [], name: "BodaBodaSavings__ZeroDeposit", type: "error" },
        { inputs: [], name: "BodaBodaSavings__ZeroLoanTarget", type: "error" },
        { inputs: [], name: "BodaBodaSavings__ZeroWithdrawAmount", type: "error" },
        { inputs: [], name: "EnforcedPause", type: "error" },
        { inputs: [], name: "ExpectedPause", type: "error" },
        {
          inputs: [{ internalType: "address", name: "owner", type: "address" }],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [{ internalType: "address", name: "account", type: "address" }],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
        {
          inputs: [{ internalType: "address", name: "token", type: "address" }],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "totalAmount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "savingsPart", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "loanPart", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
          ],
          name: "Deposit",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "token", type: "address" },
            { indexed: true, internalType: "address", name: "to", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
          ],
          name: "ERC20Recovered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "lenderAddress", type: "address" },
            { indexed: false, internalType: "string", name: "name", type: "string" },
            { indexed: false, internalType: "uint256", name: "collectionCycle", type: "uint256" },
            { indexed: false, internalType: "enum BodaBodaSavings.RepaymentSchedule", name: "schedule", type: "uint8" },
          ],
          name: "LenderAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "lenderAddress", type: "address" },
            { indexed: false, internalType: "uint256", name: "newCycle", type: "uint256" },
          ],
          name: "LenderCycleUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [{ indexed: true, internalType: "address", name: "lenderAddress", type: "address" }],
          name: "LenderDeactivated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [{ indexed: true, internalType: "address", name: "lenderAddress", type: "address" }],
          name: "LenderReactivated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "totalRepaid", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "clearedAt", type: "uint256" },
          ],
          name: "LoanCleared",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "oldTarget", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "newTarget", type: "uint256" },
          ],
          name: "LoanTargetUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
            { indexed: true, internalType: "address", name: "newOwner", type: "address" },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
          name: "Paused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "settledAt", type: "uint256" },
          ],
          name: "PotAutoSettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "excess", type: "uint256" },
          ],
          name: "PotExcessReturned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "lockedAt", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "intendedPayAt", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "autoDeadline", type: "uint256" },
          ],
          name: "PotLocked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "releasedAt", type: "uint256" },
          ],
          name: "PotReleasedByRider",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint8", name: "newLevel", type: "uint8" },
          ],
          name: "RiderKYCUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "string", name: "name", type: "string" },
            { indexed: true, internalType: "address", name: "lender", type: "address" },
            { indexed: false, internalType: "uint256", name: "loanTarget", type: "uint256" },
            { indexed: false, internalType: "uint8", name: "kycLevel", type: "uint8" },
            { indexed: false, internalType: "enum BodaBodaSavings.SplitRatio", name: "splitRatio", type: "uint8" },
          ],
          name: "RiderRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "oldStablecoin", type: "address" },
            { indexed: true, internalType: "address", name: "newStablecoin", type: "address" },
          ],
          name: "StablecoinUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
          name: "Unpaused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "approvedAt", type: "uint256" },
          ],
          name: "WithdrawalApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "cancelledAt", type: "uint256" },
          ],
          name: "WithdrawalCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "claimedAt", type: "uint256" },
          ],
          name: "WithdrawalClaimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "deniedAt", type: "uint256" },
          ],
          name: "WithdrawalDenied",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            { indexed: true, internalType: "address", name: "rider", type: "address" },
            { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
            { indexed: false, internalType: "bytes32", name: "category", type: "bytes32" },
            { indexed: false, internalType: "uint256", name: "requestedAt", type: "uint256" },
          ],
          name: "WithdrawalRequested",
          type: "event",
        },
        {
          inputs: [],
          name: "KYC_BASIC",
          outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "KYC_FULL",
          outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "KYC_PREMIUM",
          outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REASON_EDUCATION",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REASON_EMERGENCY",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REASON_FAMILY_OBLIGATION",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REASON_HOUSEHOLD",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REASON_MEDICAL",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REASON_OTHER",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REASON_REPAIR",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "WITHDRAWAL_DELAY",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "_lenderAddress", type: "address" },
            { internalType: "string", name: "_name", type: "string" },
            { internalType: "uint256", name: "_cycle", type: "uint256" },
            { internalType: "enum BodaBodaSavings.RepaymentSchedule", name: "_schedule", type: "uint8" },
          ],
          name: "addLender",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "approveWithdrawal",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        { inputs: [], name: "cancelWithdrawal", outputs: [], stateMutability: "nonpayable", type: "function" },
        { inputs: [], name: "claimWithdrawal", outputs: [], stateMutability: "nonpayable", type: "function" },
        {
          inputs: [{ internalType: "address", name: "_lenderAddress", type: "address" }],
          name: "deactivateLender",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "denyWithdrawal",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
          name: "deposit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "uint256", name: "deadline", type: "uint256" },
            { internalType: "uint8", name: "v", type: "uint8" },
            { internalType: "bytes32", name: "r", type: "bytes32" },
            { internalType: "bytes32", name: "s", type: "bytes32" },
          ],
          name: "depositWithPermit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getContractBalance",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getIdleLoanBalance",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_lenderAddress", type: "address" }],
          name: "getLender",
          outputs: [
            { internalType: "string", name: "name", type: "string" },
            { internalType: "uint256", name: "collectionCycle", type: "uint256" },
            { internalType: "enum BodaBodaSavings.RepaymentSchedule", name: "schedule", type: "uint8" },
            { internalType: "bool", name: "verified", type: "bool" },
            { internalType: "bool", name: "active", type: "bool" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getLenderCount",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "offset", type: "uint256" },
            { internalType: "uint256", name: "limit", type: "uint256" },
          ],
          name: "getLenders",
          outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "getLoanStatus",
          outputs: [
            { internalType: "uint256", name: "loanTarget", type: "uint256" },
            { internalType: "uint256", name: "loanBalance", type: "uint256" },
            { internalType: "uint256", name: "loanRepaid", type: "uint256" },
            { internalType: "uint256", name: "loanRemaining", type: "uint256" },
            { internalType: "bool", name: "isCleared", type: "bool" },
            { internalType: "uint256", name: "progressBps", type: "uint256" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getLockedPotTotal",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "getPotHistory",
          outputs: [
            {
              components: [
                { internalType: "uint256", name: "amount", type: "uint256" },
                { internalType: "uint256", name: "lockedAt", type: "uint256" },
                { internalType: "uint256", name: "settledAt", type: "uint256" },
                { internalType: "bool", name: "autoSettled", type: "bool" },
              ],
              internalType: "struct BodaBodaSavings.PotRecord[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "getRiderAnalytics",
          outputs: [
            { internalType: "uint256", name: "savingsBalance", type: "uint256" },
            { internalType: "uint256", name: "loanBalance", type: "uint256" },
            { internalType: "uint256", name: "totalDeposited", type: "uint256" },
            { internalType: "uint256", name: "totalWithdrawn", type: "uint256" },
            { internalType: "uint256", name: "withdrawalCount", type: "uint256" },
            { internalType: "uint256", name: "lastDepositAt", type: "uint256" },
            { internalType: "uint256", name: "firstDepositAt", type: "uint256" },
            { internalType: "bool", name: "potActive", type: "bool" },
            { internalType: "uint256", name: "potBalance", type: "uint256" },
            { internalType: "uint256", name: "potLockedAt", type: "uint256" },
            { internalType: "uint256", name: "potDeadline", type: "uint256" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "getRiderKYC",
          outputs: [
            { internalType: "bytes32", name: "verificationHash", type: "bytes32" },
            { internalType: "uint8", name: "verificationLevel", type: "uint8" },
            { internalType: "uint256", name: "verifiedAt", type: "uint256" },
            { internalType: "uint256", name: "licenseExpiry", type: "uint256" },
            { internalType: "bytes32", name: "kycProvider", type: "bytes32" },
            { internalType: "bool", name: "verified", type: "bool" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "getRiderProfile",
          outputs: [
            { internalType: "string", name: "name", type: "string" },
            { internalType: "uint8", name: "age", type: "uint8" },
            { internalType: "bytes1", name: "gender", type: "bytes1" },
            { internalType: "bool", name: "registered", type: "bool" },
            { internalType: "address", name: "lenderAddress", type: "address" },
            { internalType: "string", name: "lenderName", type: "string" },
            { internalType: "enum BodaBodaSavings.RepaymentSchedule", name: "lenderSchedule", type: "uint8" },
            { internalType: "enum BodaBodaSavings.SplitRatio", name: "splitRatio", type: "uint8" },
            { internalType: "uint256", name: "loanTarget", type: "uint256" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "getWithdrawalHistory",
          outputs: [
            {
              components: [
                { internalType: "uint256", name: "amount", type: "uint256" },
                { internalType: "bytes32", name: "category", type: "bytes32" },
                { internalType: "uint256", name: "requestedAt", type: "uint256" },
                { internalType: "uint256", name: "claimedAt", type: "uint256" },
              ],
              internalType: "struct BodaBodaSavings.WithdrawalRecord[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "getWithdrawalRequest",
          outputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "bytes32", name: "category", type: "bytes32" },
            { internalType: "uint256", name: "requestedAt", type: "uint256" },
            { internalType: "uint256", name: "approvedAt", type: "uint256" },
            { internalType: "uint256", name: "claimableAt", type: "uint256" },
            { internalType: "enum BodaBodaSavings.WithdrawalStatus", name: "status", type: "uint8" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "isVerifiedRider",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          name: "lenderList",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "lenders",
          outputs: [
            { internalType: "string", name: "name", type: "string" },
            { internalType: "address", name: "lenderAddress", type: "address" },
            { internalType: "uint256", name: "collectionCycle", type: "uint256" },
            { internalType: "enum BodaBodaSavings.RepaymentSchedule", name: "schedule", type: "uint8" },
            { internalType: "bool", name: "verified", type: "bool" },
            { internalType: "bool", name: "active", type: "bool" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "uint256", name: "intendedPayAt", type: "uint256" },
          ],
          name: "lockToPot",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [{ internalType: "address", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
        {
          inputs: [],
          name: "paused",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_lenderAddress", type: "address" }],
          name: "reactivateLender",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "_token", type: "address" },
            { internalType: "address", name: "_to", type: "address" },
            { internalType: "uint256", name: "_amount", type: "uint256" },
          ],
          name: "recoverERC20",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "string", name: "_name", type: "string" },
            { internalType: "uint8", name: "_age", type: "uint8" },
            { internalType: "bytes1", name: "_gender", type: "bytes1" },
            { internalType: "address", name: "_lenderAddress", type: "address" },
            { internalType: "enum BodaBodaSavings.SplitRatio", name: "_ratio", type: "uint8" },
            { internalType: "uint256", name: "_loanTarget", type: "uint256" },
            { internalType: "bytes32", name: "_verificationHash", type: "bytes32" },
            { internalType: "uint8", name: "_kycLevel", type: "uint8" },
            { internalType: "uint256", name: "_licenseExpiry", type: "uint256" },
            { internalType: "bytes32", name: "_kycProvider", type: "bytes32" },
          ],
          name: "registerRider",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        { inputs: [], name: "releaseFromPot", outputs: [], stateMutability: "nonpayable", type: "function" },
        { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
        {
          inputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "bytes32", name: "category", type: "bytes32" },
          ],
          name: "requestWithdrawal",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "revokeApprovedWithdrawal",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "riderKYC",
          outputs: [
            { internalType: "bytes32", name: "verificationHash", type: "bytes32" },
            { internalType: "uint8", name: "verificationLevel", type: "uint8" },
            { internalType: "bool", name: "verified", type: "bool" },
            { internalType: "uint256", name: "verifiedAt", type: "uint256" },
            { internalType: "uint256", name: "licenseExpiry", type: "uint256" },
            { internalType: "bytes32", name: "kycProvider", type: "bytes32" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "riders",
          outputs: [
            { internalType: "string", name: "name", type: "string" },
            { internalType: "bytes1", name: "gender", type: "bytes1" },
            { internalType: "address", name: "lenderAddress", type: "address" },
            { internalType: "enum BodaBodaSavings.SplitRatio", name: "splitRatio", type: "uint8" },
            { internalType: "uint256", name: "loanTarget", type: "uint256" },
            { internalType: "uint256", name: "loanBalance", type: "uint256" },
            { internalType: "uint256", name: "loanRepaid", type: "uint256" },
            { internalType: "uint256", name: "savingsBalance", type: "uint256" },
            { internalType: "uint256", name: "totalDeposited", type: "uint256" },
            { internalType: "uint256", name: "totalWithdrawn", type: "uint256" },
            { internalType: "uint256", name: "withdrawalCount", type: "uint256" },
            { internalType: "uint256", name: "lastDepositAt", type: "uint256" },
            { internalType: "uint256", name: "firstDepositAt", type: "uint256" },
            { internalType: "uint256", name: "potBalance", type: "uint256" },
            { internalType: "uint256", name: "potLockedAt", type: "uint256" },
            { internalType: "uint256", name: "potDeadline", type: "uint256" },
            { internalType: "uint8", name: "age", type: "uint8" },
            { internalType: "bool", name: "potActive", type: "bool" },
            { internalType: "bool", name: "registered", type: "bool" },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_stablecoin", type: "address" }],
          name: "setStablecoin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "_rider", type: "address" }],
          name: "settleExpiredPot",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "stablecoin",
          outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalLoanCredits",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalLoanSettled",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalLockedInPots",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSavingsHeld",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
        {
          inputs: [
            { internalType: "address", name: "_lenderAddress", type: "address" },
            { internalType: "uint256", name: "_newCycle", type: "uint256" },
          ],
          name: "updateLenderCycle",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "_rider", type: "address" },
            { internalType: "uint256", name: "_newTarget", type: "uint256" },
          ],
          name: "updateLoanTarget",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            { internalType: "address", name: "_rider", type: "address" },
            { internalType: "bytes32", name: "_newHash", type: "bytes32" },
            { internalType: "uint8", name: "_newLevel", type: "uint8" },
            { internalType: "uint256", name: "_newLicenseExpiry", type: "uint256" },
            { internalType: "bytes32", name: "_kycProvider", type: "bytes32" },
          ],
          name: "updateRiderKYC",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "withdrawalRequests",
          outputs: [
            { internalType: "uint256", name: "amount", type: "uint256" },
            { internalType: "bytes32", name: "category", type: "bytes32" },
            { internalType: "uint256", name: "requestedAt", type: "uint256" },
            { internalType: "uint256", name: "approvedAt", type: "uint256" },
            { internalType: "enum BodaBodaSavings.WithdrawalStatus", name: "status", type: "uint8" },
          ],
          stateMutability: "view",
          type: "function",
        },
      ] as const,
    },
  },
} as const;

export default externalContracts satisfies GenericContractsDeclaration;
